### ISSUE TITLE
[PE-D][Tester C] Find command message not updating

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-F12-1/tp#151] opened 2024-04-05 18:41 UTC
![Screenshot 2024-04-05 at 4.42.59 PM.png](https://raw.githubusercontent.com/kaitinghh/ped/main/files/b41b792f-d452-4190-b57b-9863920477e1.png)

The find command should return a corresponding results display message, but it is not showing. It shows the previous command display message instead. 

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: kaitinghh/ped#10

**Comment by shaunlxw** [comment] 2024-04-11 17:25
Closing as duplicate of #140.

**Closed as completed by shaunlxw** 2024-04-11 17:25 UTC
